### ISSUE TITLE
already done work

### ISSUE THREAD

**Issue by zeroKilo** [Aim4kill/BlazeSDK#1]
https://github.com/zeroKilo/BF1SuckerWV/blob/master/BF1SuckerWV/Blaze.cs
https://github.com/zeroKilo/BFP4FToolsWV/wiki/Research-Information#blaze
https://github.com/Tratos/New-Blaze-Emulator

in case you dont wanna redo all the work from scratch :)
 
greetz WV

**Comment by Aim4kill** [comment]
Hello!

Thanks for the links, but I prefer to do my own research, because I am trying to do everything properly and want to make sure nothing is missed.
Furthemore, the reason why I am making everything from scratch is because looking at the current existing blaze servers, both in C# and Python, they use Tdf tags, where it is not always clear what exactly does it mean (what value it is holding). One of my goals is to enable for devs to see what exactly is in the packet and what exactly is each field.

Here below you can see example CreateGameRequest where you can see all packet data (this is from my own blaze server, which source code i am not planning yet to share, however, later will try to add some examples on how to get started with this SDK).
<img width="929" alt="image" src="https://user-images.githubusercontent.com/76944477/225026166-6a031353-f970-45d0-9c93-a9e52c1cdb92.png">

Another reason why i am making everything from scratch is because then handling blaze packets gets much easier, you don't have to think about what tags you need to read + what types are they+ you know the actual limits of integer types (you can't encode larger integer values than the specified type max limit even though tdf varsize integer encoding allows it). There are also other reasons, but i can't go through them all right now. For example look how much simpler it gets responding to PostAuth request (from my blaze server source), it just looks much better.
<img width="523" alt="image" src="https://user-images.githubusercontent.com/76944477/225035969-2084b4fb-5239-4b37-b30f-5875f7461879.png">


Also right now there is not much to research, the biggest issue right now is adding all of the tdf struct data (for example like CreateGameRequest, PostAuthResponse that i just showed you, etc.) to SDK in order to support ~~all~~ most of blaze requests and responses.

Thank you for your interest!

**Comment by zeroKilo** [comment]
Well you dont have to show me your research, I literally done all this before, multiple times, for different games and could explain it too, aka why I made a wiki for others, but go ahead and reinvent the wheel, have fun. greetz WV

**Comment by Aim4kill** [comment]
I think you misunderstood me. The work you have done is nice, but you need to understand that I personally want to learn too how everything works under the hood. Truth be told, actually long time ago I did look at other people's projects in order to understand how it all works, but sometimes I did notice things, that is incorrect assumptions about how certain things worked, which is also one of the reasons why i am doing everything from scratch and researching same things again. I am simply creating this to satisfy my needs and requirements :)

**Comment by zeroKilo** [comment]
Again, you could just ASK someone who already has done YEARS of this re, like reversing the actual blaze code and writing working servers for multiple games, plus making writeups for ppl like you but sure tell me how bad my code is, that you can do everything better and from scratch and dont even need to give credit or say thanks to the ppl that came before you. lets ignore the fact that blaze has different formats for different games, that the TDF field names are hardcoded to match in the game, so you cant simply invent new ones, or the simple fact that none if this helps you if you dont have a leaked game server, because this is just to make gameserver and game find each other, thats pretty much all blaze does. But sure, go ahead, find it all out again and then claim to be the first, congratz! Ah well, the internet repeats itself...

**Comment by Aim4kill** [comment]
If i would simply ASK someone who has already done YEARS of this re, then I personally would learn __nothing__. You have an weird interesting thinking - if someone had looked into this, then nobody else can do the same thing. Also I didnt say that your code is bad. What I meant to say is that there are many proof of concepts out there (like python blaze), but which needs improving. 

>lets ignore the fact that blaze has different formats for different games

Who said that i was ignoring it? If you had actually looked at some of my source code, you would see that im currently writing for Blaze 3 versions, for games such as bf3, nfs tr, etc, where the tdf request and response structure is the same. I already know that for different Blaze versions, there are differences such as the packet header (fireframe) (for example in BF Hardline) or tdf encoding itself (Blaze 2 uses different tdf encoding and im sure you already know this). 

>none if this helps you if you dont have a leaked game server

Yes true, but you don't always need a gameserver. Sometimes just want to look what client is sending/receiving to/from blaze. And some of the games can be run as servers too (like bf3 alpha trial or nfs tr).

>find it all out again and then claim to be the first

lol, im not the first, im just creating this the way i like it, if you can't accept this simple fact, then i can't help you.

**Comment by zeroKilo** [comment]
dude just do me a favour and delete this entire issue, im sorry for trying to help, wont happen again

PS: "If i would simply ASK someone who has already done YEARS of this re, then I personally would learn nothing. " great quote, I hope you tell that every teacher you ever had, to make him/her regret helping you too

**Comment by Aim4kill** [comment]
You know reverse engineering is something you have to do yourself in order to learn it better. If you simply watch thousand tutorials where people already have come up with answers, then when the real thing comes to re, then without any practicing on same things earlier... good luck.

**Comment by zeroKilo** [comment]
"You know reverse engineering is something..."

what a fucking smug answer, I wasnt saying I give you all the answer, "here do this do that do whatever..." I wanted to help you with problems you may have, the stuff you dont find anywhere and how to approach it, how to use the tools available, how to make tools, saving you all the watchtime of off-topic tutorials, or reading the same stuff talking about the same topic for the 50th time, I literally made a tutorial series how to reverse games IN GENERAL, so yes you still have to apply it to your particular game, but the fucking steps are the same! sure, find that all out AGAIN, and ON YOUR OWN, you literally make enemies here by talking like that. 

Fine, do it all alone, but dont be so smug about yourself and to the people that offer help, dont try to teach me stuff I could teach you about! "rEaD mY CoDe"... but cant spend a second to find out who you talk to or what I linked.

its great if you wanna learn on your own, im all for it, just say "thanks, but I wanna find out myself", not "fuck you and your expirience/knowledge I will make it all better" ...you really piss people off here (not just me)

and JUST DELETE THIS ISSUE, I dont even want a reply from you, just fucking delete this issue and we all can happily move on, THANKS!

**Comment by Aim4kill** [comment]
The point of creating issues here is to resolve them. And I won't delete this issue, until we resolve it, because I think we got on the wrong foot here, also I don't want to create enemies.

Like i said before, this whole thing is a big misunderstanding.

>its great if you wanna learn on your own, im all for it, just say "thanks, but I wanna find out myself"

Thats was the first sentence i actually said in my first response : "Thanks for the links, but I prefer to do my own research, because I am trying to do everything properly and want to make sure nothing is missed.". I apologize if this did seem like 
"fuck you and your expirience/knowledge I will make it all better", because that is not what i meant with that. So thank you, I appreciate the help, but i want to find out things on my own.

>but cant spend a second to find out who you talk to or what I linked.

Actually, I do. I have seen your work, your videos in your youtube channel. Its great stuff you have done! 👍 :)
